apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hdfs-k8s.namenode.fullname" . }}
  labels:
    {{- include "hdfs-k8s.selectorLabels" . | nindent 4 }}
    app: {{ include "hdfs-k8s.namenode.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "hdfs-k8s.namenode.fullname" . }}
      {{- include "hdfs-k8s.selectorLabels" . | nindent 6 }}
  minAvailable: 1