apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs-k8s.journalnode.fullname" . }}
  labels:
    {{- include "hdfs-k8s.selectorLabels" . | nindent 4 }}
    app: {{ template "hdfs-k8s.journalnode.fullname" . }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: jn
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "hdfs-k8s.selectorLabels" . | nindent 4 }}
    app: {{ template "hdfs-k8s.journalnode.fullname" . }}