apiVersion: v2
name: hdfs-k8s
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "3.3.6"

dependencies:
  - name: journalnode
    version: 0.1.0
    repository: "file://../journalnode"
  - name: namenode
    version: 0.1.0
    repository: "file://../namenode"
  - name: datanode
    version: 0.1.0
    repository: "file://../datanode"