apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hdfs-k8s.journalnode.fullname" . }}
  labels:
    {{- include "hdfs-k8s.selectorLabels" . | nindent 4 }}
    app: {{ include "hdfs-k8s.journalnode.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "hdfs-k8s.journalnode.fullname" . }}
      {{- include "hdfs-k8s.selectorLabels" . | nindent 6 }}
  minAvailable: {{ div .Values.global.journalnodeQuorumSize 2 | add1 }}